### ISSUE TITLE
[Feature] Command for all available canteens

### ISSUE THREAD

**Issue by COM8** [srehwald/eat-api#10]
A command that returns all available canteens in a Json array would be great to automate the process of requesting all menus for all canteens.

Examle output:

[
    {
         "name":"Mensa Arcisstraße",
         "address":"Arcisstr. 17, München",
         "latitude":"48.147312",
         "longitude":"11.567229"
      },
      {
         "name":"Mensa Garching",
         "address":"Lichtenbergstr. 2, Garching",
         "latitude":"48.267509",
         "longitude":"11.671278"
      },
	  [...]
   ]

**Comment by srehwald** [comment]
would you suggest to also host the output statically on gh-pages (same as the menus) or just a command for the cli?

**Comment by COM8** [comment]
Sure why not.
Although I tend to use your tool on my own server.
But I'm probably not the only person that will use this feature for automatic menu requests.😉

**Comment by COM8** [comment]
I've created a .json for all available canteens:
[https://home.in.tum.de/~sauterf/dist/canteens.json](https://home.in.tum.de/~sauterf/dist/canteens.json)

**Comment by srehwald** [comment]
Thanks, that makes it easier for me.
I am planning to implement it in a way that the user specifies a path to a file which the locations-json will be written to. Does this meet your expectations?

**Comment by COM8** [comment]
Yes it does.
