### ISSUE TITLE
FMI Title Garching-Speiseplan → Garching_Speiseplan

### ISSUE THREAD

**Issue by raabf** [srehwald/eat-api#12]
Since new year FMI Bistro changed the title (snippet from bistro homepage):

      <a href="http://www.wilhelm-gastronomie.de/wp-content/uploads/2017/12/Garching_Speiseplan_KW02_2018.pdf">Garching_Speiseplan_KW02_2018</a>

https://github.com/srehwald/eat-api/blob/35fa5d2e72e4c7db98f7e584118dbe622fe6c567/src/menu_parser.py#L164

So just change Garching-Speiseplan → Garching_Speiseplan and it works (I spare a MR just for one line). Let’s hope this change is persistent.

**Comment by srehwald** [comment]
Fix it in the new release. Thank you for reporting it!
