### ISSUE TITLE
Mediziner Mensa 

### ISSUE THREAD

**Issue by kordianbruck** [srehwald/eat-api#21]
> könnt ihr auch die MedizinerMensa im rechts der Isar dazunehmen?

https://www.med.fs.tum.de/index.php?id=5
bottom right. 

https://www.med.fs.tum.de/fileadmin/w00bps/www/Daten/Mensaplan/KW_08_Winter_3_Mensa_Aktion_Huettenschmankerl.pdf

Sync to/from: https://github.com/jpbernius/FMeat.php/issues/2

**Comment by srehwald** [comment]
In general yes and I'm happy to implement it. Just depends on how well the text of the pdf allows for a proper extraction of the dishes. I'll have a look at it in the few next days.

**Comment by kordianbruck** [comment]
The PDF looks good, as in one can copy the data from there / its selectable. I'm not sure, how consistent the PDFs are - thats really my only conern.

**Comment by srehwald** [comment]
Apparently, they removed the PDF from https://www.med.fs.tum.de/index.php?id=5 . Maybe due to the end of the semester or they just forgot to add a new one. In any case, I need to wait until I have some of their menus at hand.

**Comment by kordianbruck** [comment]
Here is one of them

[KW_16_Fruehling_Mensa_2_-_2018.pdf](https://github.com/srehwald/eat-api/files/1917442/KW_16_Fruehling_Mensa_2_-_2018.pdf)

**Comment by kordianbruck** [comment]
Any updates? Is it feasible that we integrate this for the new semester?

**Comment by srehwald** [comment]
Alright. Got time now. Is https://www.med.fs.tum.de/index.php?id=5 still the right link? I can't find the menu there.

**Comment by srehwald** [comment]
ok nevermind. They have now uploaded the current menu.

**Comment by kordianbruck** [comment]
Great, I asked the contact person at the Isar, but they did not yet reply.

**Comment by srehwald** [comment]
Update: I implemented a first version that works for the current menu. I'll wait for next week's menu and add some more test cases.

@kordianbruck does your contact person know the prices for the "non-Extraessen" dishes?

**Comment by srehwald** [comment]
My parser works for the current week as well. Will prepare release within the next days

**Comment by srehwald** [comment]
Mediziner mensa is now supported (pull request #40).
However, prices are still missing (issue #41 ).
