### ISSUE TITLE
IPP: „risch“ statt „Frisch“

### ISSUE THREAD

**Issue by jpbernius** [srehwald/eat-api#28]
https://github.com/srehwald/eat-api/blob/gh-pages/ipp-bistro/2018/12.json

**Comment by srehwald** [comment]
Probably, the dish name was a litte longer than usual. This is a little difficult to fix as the parser might not be able to tell to which column a specific character belongs to in such a case. As this was 3 weeks ago and the menu changed anyway, I assume I can close this (known) issue.
