### ISSUE TITLE
Crash while parsing fmi-bistro for KW14

### ISSUE THREAD

**Issue by laramarie** [srehwald/eat-api#32]
The plan for the current week (KW14) in the FMI bistro has problems being parsed and is missing in the api. Might be because one day is a holiday or because they added additional links on their website?

[Garching_Speiseplan_KW_14_20181.pdf](https://github.com/srehwald/eat-api/files/1880352/Garching_Speiseplan_KW_14_20181.pdf)

**Comment by raabf** [comment]
No the empty Monday column can be handled by the parser, that's OK.

However the multiple PDF on the page is indeed a problem:

https://github.com/srehwald/eat-api/blob/de4f4c57e149e4850f4f821ca69b70270f5994eb/src/menu_parser.py#L164-L165

The program is expecting only one PDF (like it was until yet)

However there is a second problem:

    Garching_Speiseplan_KW_14_20181
    Garching_Speiseplan_KW_15_20181

(see the appended 1 at the end of the year)

See #31 for a fix of both of the problems
