### ISSUE TITLE
FMI: Restructured Menu with "Suppe", "VEGAN", "Vegetarisch", "Fleisch/ Fisch" & "Aktion" leads to "Fleisch/ Fisch" not being pared.

### ISSUE THREAD

**Issue by jpbernius** [srehwald/eat-api#36]
New Menu:
- [KW 25](https://www.wilhelm-gastronomie.de/wp-content/uploads/2018/06/Garching_Speiseplan_KW_25_2018.pdf)
- [KW 24](https://www.wilhelm-gastronomie.de/wp-content/uploads/2018/05/Garching_Speiseplan_KW_24_2018.pdf)
- [KW 23](https://www.wilhelm-gastronomie.de/wp-content/uploads/2018/05/Garching_Speiseplan_KW_23_2018.pdf)

Latest build 9f939e3 does not contain the dishes listed as *Fleisch/ Fisch*.

**Comment by srehwald** [comment]
should now be fixed by eb6022443aa6a7a616c440f4ebb7e65213a2ed4f
