### ISSUE TITLE
IPP menu parsing

### ISSUE THREAD

**Issue by COM8** [srehwald/eat-api#4]
Would it be possible for you to parse the IPP menu as well?
http://konradhof-catering.de/ipp/

If it's possible, I might switch to you API.
Your API looks like it has a lot of potential. Great work :)
--> [UWP-TUM-Campus-App](https://github.com/COM8/UWP-TUM-Campus-App)

**Comment by srehwald** [comment]
Thanks!
It is definitely possible. I have already been playing around with it. I just need to find a way to cope with the table structure.

**Comment by srehwald** [comment]
The new release will support the IPP Bistro. There are still some minor issues, but the parsing works reasonably well.

**Comment by COM8** [comment]
Sounds great, I will have a look at it soon.
